# -*- coding: utf-8 -*-
"""beautys3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgqY4tgjbXr_BM5bhDo1XdV7e5mEf_TZ
"""

import pandas as pd
from google.colab import files

# Subir archivo
uploaded = files.upload()
filename = next(iter(uploaded))
df = pd.read_csv(filename, encoding='ISO-8859-1', delimiter='|')

# Limpiar nombres de columnas
df.columns = df.columns.str.strip()

# Identificar todas las sucursales disponibles
stock_columns = [col for col in df.columns if 'minimo de sucursal [' in col]
sucursales = [col.split('[')[1].replace(']', '') for col in stock_columns]

print("\nSucursales disponibles:", ", ".join(sucursales))

# Pedir inputs al usuario
print("\nIngrese los datos requeridos:")
sucursal_destino = input("Sucursal DESTINO (solo el nombre, ej: ): ").strip()
stock_minimo = float(input("Stock mínimo deseado en destino (puede ser decimal): "))
venta_minima = float(input("Venta mínima para considerar (puede ser decimal): "))

# Verificar sucursal destino - BUSCAR COINCIDENCIA EXACTA
col_destino = None
for col in stock_columns:
    if sucursal_destino in col:
        col_destino = col
        break

if col_destino is None:
    raise ValueError(f"No se encontró datos para la sucursal {sucursal_destino}")

print(f"Columna destino encontrada: {col_destino}")

# Convertir columnas a numéricas (manejando decimales)
for col in stock_columns + ['Venta']:
    df[col] = pd.to_numeric(df[col].str.replace(',', '.'), errors='coerce').fillna(0)

print("\nValores convertidos a numéricos:")
print(df[stock_columns + ['Venta']].head())

# Filtrar productos que necesitan stock
necesitan_stock = df[
    (df[col_destino] < stock_minimo) &
    (df['Venta'] >= venta_minima)
].copy()

print(f"\nProductos que necesitan stock en {sucursal_destino}: {len(necesitan_stock)}")
if len(necesitan_stock) > 0:
    print(necesitan_stock[['Descripcion', col_destino, 'Venta']].head())

# Prioridad de sucursales origen (Exp primero, luego las demás por stock)
sucursales_origen = [s for s in sucursales if s != sucursal_destino]
if 'Exp' in sucursales_origen:
    sucursales_origen.remove('Exp')
    sucursales_origen = ['Exp'] + sucursales_origen

# Función para calcular transferencia
def calcular_transferencia(row):
    faltante = max(stock_minimo - row[col_destino], 0)

    for sucursal in sucursales_origen:
        col_origen = f'Mín Auto [{sucursal}]'
        stock_disponible = row[col_origen]
        if stock_disponible > 0:
            transferir = min(faltante, stock_disponible)
            return {
                'Producto': row['Descripcion'],
                'Ventas': row['Venta'],
                f'Stock en {sucursal_destino}': row[col_destino],
                'Sucursal Origen': sucursal,
                'Stock en Origen': stock_disponible,
                'Transferir': transferir
            }

    return {
        'Producto': row['Descripcion'],
        'Ventas': row['Venta'],
        f'Stock en {sucursal_destino}': row[col_destino],
        'Sucursal Origen': 'Sin stock disponible',
        'Stock en Origen': 0,
        'Transferir': 0
    }

# Aplicar cálculo
resultado = []
for _, row in necesitan_stock.iterrows():
    resultado.append(calcular_transferencia(row))

resultado = pd.DataFrame(resultado)

# Filtrar solo transferencias posibles
resultado = resultado[resultado['Transferir'] > 0]

if len(resultado) == 0:
    print("\nNo hay sucursales origen con stock suficiente para transferir")
    if len(necesitan_stock) > 0:
        print("\nProductos que necesitan stock pero no tienen origen disponible:")
        print(necesitan_stock[['Descripcion', col_destino, 'Venta'] +
                            [f'Mín Auto [{s}]' for s in sucursales_origen]].head())
else:
    # Ordenar por cantidad a transferir (mayor a menor)
    resultado = resultado.sort_values(by='Transferir', ascending=False)

    # Exportar a Excel
    output_filename = f"Transferencias_a_{sucursal_destino}.xlsx"
    resultado.to_excel(output_filename, index=False)

    print(f"\nResumen de transferencias:")
    print(resultado.head())
    print(f"\nTotal productos a transferir: {len(resultado)}")
    print(f"Archivo generado: {output_filename}")

    # Descargar
    files.download(output_filename)